import streamlit as st
from io import BytesIO
from datetime import datetime
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


def show_report(score, confidence, fluency, clarity, summary):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    # ---------------- Title ----------------
    story.append(
        Paragraph(
            "<b>VOICE BASED CONCEPT UNDERSTANDING ANALYZER</b>",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "<b>AI Generated Student Performance Report</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 15))

    # ---------------- Overall Score ----------------
    overall = round((score + confidence + fluency + clarity) / 4, 2)

    story.append(
        Paragraph(
            f"<b>Overall Score :</b> {overall}%",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 12))

    # ---------------- Performance Metrics ----------------
    story.append(
        Paragraph("<b>Performance Metrics</b>", styles["Heading2"])
    )

    story.append(Paragraph(f"Concept Score : {score}%", styles["Normal"]))
    story.append(Paragraph(f"Confidence : {confidence}%", styles["Normal"]))
    story.append(Paragraph(f"Fluency : {fluency}%", styles["Normal"]))
    story.append(Paragraph(f"Clarity : {clarity}%", styles["Normal"]))

    story.append(Spacer(1, 15))

    # ---------------- AI Summary ----------------
    story.append(
        Paragraph("<b>AI Generated Summary</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(summary, styles["Normal"])
    )

    story.append(Spacer(1, 15))

    # ---------------- Final Evaluation ----------------
    if overall >= 90:
        performance = "Excellent"
    elif overall >= 75:
        performance = "Very Good"
    elif overall >= 60:
        performance = "Good"
    else:
        performance = "Needs Improvement"

    story.append(
        Paragraph("<b>Final Evaluation</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            f"Overall Performance : {performance}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "Recommendation : Continue practicing to improve communication skills and maintain conceptual clarity.",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # ---------------- Footer ----------------
    story.append(
        Paragraph(
            "<b>Generated by VCUA AI System</b>",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"Date : {datetime.now().strftime('%d-%m-%Y')}",
            styles["Normal"]
        )
    )

    doc.build(story)

    st.download_button(
        "📄 Download PDF Report",
        data=buffer.getvalue(),
        file_name="AI_Report.pdf",
        mime="application/pdf"
    )
    